# Generated by Django 3.1.5 on 2021-02-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algo_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('web_id', models.CharField(max_length=45, unique=True)),
                ('discord_id', models.CharField(max_length=45, unique=True)),
                ('student_id', models.CharField(max_length=45, unique=True)),
                ('baekjoon_id', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=45, unique=True)),
                ('student_id', models.CharField(max_length=45, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('point', models.IntegerField()),
                ('map_location', models.IntegerField()),
                ('status', models.IntegerField()),
                ('items', models.TextField(blank=True, null=True)),
                ('daily_steps', models.IntegerField(blank=True, null=True)),
                ('baekjoon_id', models.CharField(blank=True, max_length=45, null=True)),
                ('bj_solved', models.TextField(blank=True, null=True)),
                ('bj_solv_contd', models.IntegerField()),
                ('bj_rank', models.CharField(blank=True, max_length=45, null=True)),
                ('bj_today', models.IntegerField()),
            ],
        ),
    ]
