# Generated by Django 3.1.5 on 2021-02-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
    ]
