# Generated by Django 3.1.5 on 2021-02-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
    ]
