# Generated by Django 3.1.5 on 2021-01-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '알고알고 게시글', 'verbose_name_plural': '알고알고 게시글들'},
        ),
        migrations.AlterModelTable(
            name='board',
            table='algoalgo_board',
        ),
    ]
