# Generated by Django 3.1.5 on 2021-02-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210127_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '알고알고 게시판', 'verbose_name_plural': '알고알고 게시판'},
        ),
    ]
