# Generated by Django 3.1.5 on 2021-02-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210202_0322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
    ]
